### ISSUE TITLE
Determine XML library to base this on

### ISSUE THREAD

**Issue by frewsxcv** [georust/rust-gpx#1]
No need to reinvent the wheel with our own XML parser. I'm sure there are already a few, which one should we use?

**Comment by skj3gg** [comment]
Option 1: [netvl/xml-rs](https://github.com/netvl/xml-rs) seems like a decent library with a better start at documentation than others I've seen, and has a group of devs. Was 1.0 alpha ready hours after release.
Has limitations but is near xml-1.0 compliment. Check out the [issues](https://github.com/netvl/xml-rs/issues) for some of these limitations

**Comment by frewsxcv** [comment]
Yeah, at least for now, that looks like a pretty good choice. Depending on when this particular project (rust-gpx) starts, new libraries might be available providing us with a greater selection

**Comment by frewsxcv** [comment]
There's also https://github.com/Florob/RustyXML

**Comment by shivanth** [comment]
Looks like RustyXML is not active any more.
How about https://github.com/netvl/xml-rs ?

**Comment by frewsxcv** [comment]
https://github.com/tafia/quick-xml is also an option

**Comment by shivanth** [comment]
Looks like there are a lot of xml-libraries around. Is there one in std library or something ? Spoilt for choices :-)

**Comment by shivanth** [comment]
Is there any high level architecture for the georust project as such, so as to allow interoperability between the libraries. I am looking at implementing a reader and writer for GPX files .

**Comment by frewsxcv** [comment]
Currently, the idea is for https://github.com/georust/rust-geo to be the common geographic primitives connecting all the GeoRust projects. If you have suggestions for improvement, let me know :)

**Comment by brendanashworth** [comment]
I've just pushed the first commit that implements a basic parser: https://github.com/georust/rust-gpx/commit/67ca09b98e980cb042762b2db431aaa2bd2a9d51. Right now I've chosen to use [xml-rs](https://github.com/netvl/xml-rs), but AFAIK it's not the fastest available parser. We can consider changing in the future, but for now I think this can be closed.
